name: Scrape latest forex data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '1,5 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      env:
        API_KEY: ${{secrets.API_KEY}}
      run: |-
        curl "http://data.fixer.io/api/latest?access_key=$API_KEY" | jq . > forex.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
